version: "2"

services:
  web:
    build: php7/.
#    build: php56/.
#    image: php7
    ports:
      - "8081:80"
    volumes:
      - ./drupal:/srv
    links:
      - mysql:mysql
      - mailhog:mailhog
    depends_on:
      - mysql
      - mailhog
    restart: always
    command: php -t /srv -S 0.0.0.0:80 .ht.router.php
    networks:
      - back
      - front

  mysql:
    image: percona:5.6
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: d8
      MYSQL_USER: d8
      MYSQL_PASSWORD: d8
      MYSQL_ROOT_PASSWORD: d8root
    restart: always
    networks:
      - back

  mailhog:
    image: diyan/mailhog
    restart: always
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
